services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: UBA.Panel.Azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - uba_panel
  uba.panel.report.database:
    image: postgres:latest
    hostname: reports_db
    container_name: UBA.Panel.Reports.Db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - uba_panel
  uba.panel.report.api:
    image: uba.panel.report.api
    container_name: UBA.Panel.Reports.Api
    hostname: reports
    ports:
      - 8001:80
    build:
      context: .
      dockerfile: Services/Reports/UBA.Panel.Report.Api/Dockerfile
    depends_on:
      - uba.panel.report.database
      - azurite
    networks:
      - uba_panel
  uba.panel.report.fileprocessor.functions:
    image: ${DOCKER_REGISTRY-}ubapanelreportfileprocessorfunctions
    build:
      context: .
      dockerfile: Services/Reports/UBA.Panel.Report.FileProcessor.Functions/Dockerfile
    depends_on:
      - uba.panel.report.database
      - azurite
    networks:
      - uba_panel
networks:
  uba_panel:
volumes:
  db:
    driver: local

