# This is a generated file. Not intended for manual editing.
services:
  uba.panel.report.api:
    build:
      context: "/Volumes/LACIE/projects/dotnet/UBAPanel"
      dockerfile: "Services/Reports/UBA.Panel.Report.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "uba.panel.report.api:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "/Users/maciej/.nuget/packages:/root/.nuget/packages"
    - "/Volumes/LACIE/projects/dotnet/UBAPanel/Services/Reports/UBA.Panel.Report.Api:/app:rw"
    - "/Volumes/LACIE/projects/dotnet/UBAPanel:/src:rw"
    - "/Users/maciej/.local/share/JetBrains/RiderRemoteDebugger/2023.3.2/LinuxArm64:/opt/rider-debugger"
    - "/Volumes/LACIE/Apps/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/maciej/Library/Logs/JetBrains/Rider2023.3/DebuggerWorker/JetBrains.Debugger.Worker.2023_12_31_13_06_55:/var/opt/rider-debugger:rw"
    working_dir: "/app"
