//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBA.Panel.Report.Excel.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelTranslations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelTranslations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UBA.Panel.Report.Excel.Translations.ExcelTranslations", typeof(ExcelTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Id_Label {
            get {
                return ResourceManager.GetString("Id_Label", resourceCulture);
            }
        }
        
        internal static string Name_Label {
            get {
                return ResourceManager.GetString("Name_Label", resourceCulture);
            }
        }
        
        internal static string RegistrationDate_Label {
            get {
                return ResourceManager.GetString("RegistrationDate_Label", resourceCulture);
            }
        }
        
        internal static string Vin_Label {
            get {
                return ResourceManager.GetString("Vin_Label", resourceCulture);
            }
        }
        
        internal static string TBD_Label {
            get {
                return ResourceManager.GetString("TBD_Label", resourceCulture);
            }
        }
        
        internal static string IsElectril_Label {
            get {
                return ResourceManager.GetString("IsElectril_Label", resourceCulture);
            }
        }
        
        internal static string MappedVehicleClass_Label {
            get {
                return ResourceManager.GetString("MappedVehicleClass_Label", resourceCulture);
            }
        }
        
        internal static string CreatedAt_Label {
            get {
                return ResourceManager.GetString("CreatedAt_Label", resourceCulture);
            }
        }
        
        internal static string Remarks_Label {
            get {
                return ResourceManager.GetString("Remarks_Label", resourceCulture);
            }
        }
        
        internal static string Value_Label {
            get {
                return ResourceManager.GetString("Value_Label", resourceCulture);
            }
        }
        
        internal static string True_Value {
            get {
                return ResourceManager.GetString("True_Value", resourceCulture);
            }
        }
        
        internal static string False_Value {
            get {
                return ResourceManager.GetString("False_Value", resourceCulture);
            }
        }
    }
}
